# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title                    : "Ella's Blog"
description              : "A passionate programmer and technology enthusiast"
email                    : ellalytics@gmail.com
baseurl                  : "/blog"
# url                      : "http://127.0.0.1:4000/blog/"
url                      : "https://ellalytics.github.io"
baseurl                  : "/blog"
twitter_username         : ellalytics
github_username          : ellalytics

# Author information
author:
  avatar: "/assets/images/Ella.png"
  bio: "A passionate programmer and technology enthusiast"
  location: "San Francisco Bay Area"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ellalytics"
    - label: "Twitter"
      icon: "fa-brands fa-x-twitter"
      url: "https://twitter.com/ellalytics"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ellalytics@gmail.com"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Add this line to include latest Font Awesome
font_awesome_kit: "YOUR-KIT-CODE"  # Optional if using the default

# Add custom head scripts
head_scripts:
  - https://kit.fontawesome.com/YOUR-KIT-CODE.js

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Site settings
og_image                 : /assets/images/Ella.png
timezone                 : America/Los_Angeles
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-EMB5R38212"
    anonymize_ip         : true

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#     # - label: "Twitter"
#     #   icon: "fa-brands fa-x-twitter"
#     #   url: "https://twitter.com/ellalytics"

footer: false

include:
  - _pages

# Search
search                   : true
lunr:
  search_within_pages    : true
  search_full_content    : false

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      toc: false
      toc_label: '目录'
      toc_sticky: true


  # _jekyll (collection)
  - scope:
      path: ""
      type: jekyll
    values:
      layout: single
      toc: false
      toc_label: '目录'
      toc_sticky: true
      author_profile: false
      sidebar:
        nav: "jekyll"
  - scope:
      path: ""
      type: css
    values:
      layout: single
      toc: true
      sidebar:
        nav: "css"

# Collections
collections:
  jekyll:
    output: true
    sort_by: lesson
    permalink: /tutorials/:collection/:path/
  products:
    output: true
    permalink: /:collection/:path/
  css:

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM

mermaid: true
