# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ella's Blog
email: ellalytics@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  # Welcome to My Personal Blog

  This is my personal web space, powered by Jekyll, where I record my thoughts, share knowledge, and showcase my work.

  ## About This Blog

  Here, I'll share my programming journey and technical explorations. This blog primarily features:

  - **Technical Notes** - Insights on programming languages, frameworks, tools, and solutions to various technical challenges
  - **Daily Thoughts** - Reflections on technology, learning methods, productivity, and personal growth
  - **Project Portfolio** - Detailed documentation of my personal development projects, from concept to implementation
  - **Learning Resources** - Recommendations for valuable books, courses, and online resources I've found helpful

  ## Why Jekyll

  I chose Jekyll as my blogging platform because of its simplicity and efficiency, focusing on content rather than flashy appearance. As a technology enthusiast, I appreciate its Markdown-based writing approach and powerful customization capabilities. With GitHub Pages deployment, I can concentrate on creating content without worrying about complex server maintenance issues.

  ## Get in Touch

  If you have any questions, suggestions, or ideas about the content I share, feel free to contact me through the contact information on the blog. I look forward to connecting with like-minded friends for mutual learning and growth.

  Thank you for visiting my blog. I hope the content here brings you some inspiration and assistance!

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ellalytics.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ellalytics
github_username:  ellalytics

# Author information
author:
  name: "Ella"
  avatar: "/assets/images/bio-photo.jpg"  # Add your photo to assets/images/
  bio: "A passionate programmer and technology enthusiast"
  location: "San Francisco Bay Area"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ellalytics"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/ellalytics"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ellalytics@gmail.com"

defaults:
  # _pages
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-include-cache  # required for minimal-mistakes
  - jekyll-remote-theme
